# Generated by Django 4.1 on 2022-08-21 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oauth_token', models.CharField(max_length=255)),
                ('oauth_token_secret', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_id', models.CharField(help_text="Unique identifier for user, e.g. '1073704573'", max_length=255, unique=True, verbose_name='Twitter UID')),
                ('name', models.CharField(help_text="Twitter name of user, e.g. 'むるふぉん'", max_length=255, verbose_name='Twitter名')),
                ('screen_name', models.CharField(help_text="Twitter ID, e.g. 'murufon'", max_length=255, verbose_name='Twitter ID')),
                ('profile_image_url', models.CharField(max_length=255, null=True)),
                ('twitter_oauth_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.twitterauthtoken')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
