# Generated by Django 4.1 on 2022-08-22 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_twitteruser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitteruser',
            name='twitter_oauth_token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.twitterauthtoken'),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitter_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
